language: php

php:
  - 7.4
  - 8.0

install:
  - travis_retry composer install --no-interaction

before_script:
  - composer dump-autoload

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/php-coveralls -v
